# Generated by Django 4.2.30 on 2026-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на видео (Rutube или VK Видео)')),
                ('video_source', models.CharField(choices=[('rutube', 'Rutube'), ('vk', 'VK Видео'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник видео')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на обложку (превью)')),
                ('use_auto_thumbnail', models.BooleanField(default=False, verbose_name='Автоматически получать превью из видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Изображение проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
