# Generated by Django 6.1.1 on 2026-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_shorts',
            field=models.BooleanField(default=False, verbose_name='Вертикальное видео (Shorts/Клип)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='video_source',
            field=models.CharField(choices=[('rutube', 'Rutube'), ('vk', 'VK Видео'), ('youtube', 'YouTube'), ('vk_clip', 'VK Клип'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник видео'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на видео (Rutube, VK Видео, YouTube, VK Клип)'),
        ),
    ]
